import type { NotificationItem } from './types/types';

// TODO: Replace with Express API integration — GET /api/notifications
export const mockNotifications: NotificationItem[] = [
  {
    id: 'notif-1',
    type: 'mention',
    actorName: 'Priya Patel',
    message: 'mentioned you in a comment',
    avatarInitials: 'PP',
    avatarColor: 'var(--primary)',
    timestamp: '10:30 AM',
    group: 'today',
    isRead: false,
  },
  {
    id: 'notif-2',
    type: 'post',
    actorName: 'MERN Developers',
    message: 'has a new post: Building Scalable APIs',
    avatarInitials: 'N',
    avatarColor: 'var(--success)',
    avatarShape: 'rounded',
    timestamp: '9:15 AM',
    group: 'today',
    isRead: false,
  },
  {
    id: 'notif-3',
    type: 'reply',
    actorName: 'Rohit Yadav',
    message: 'replied to your comment',
    avatarInitials: 'RY',
    avatarColor: 'var(--info)',
    timestamp: '8:45 AM',
    group: 'today',
    isRead: false,
  },
  {
    id: 'notif-4',
    type: 'resource',
    actorName: 'TypeScript Nation',
    message: 'posted a new resource',
    avatarInitials: 'TS',
    avatarColor: 'var(--warning)',
    timestamp: '7:20 AM',
    group: 'today',
    isRead: false,
  },
  {
    id: 'notif-5',
    type: 'like',
    actorName: 'Rahul Dev',
    message: 'liked your post',
    avatarInitials: 'RD',
    avatarColor: 'var(--primary)',
    timestamp: 'Yesterday',
    group: 'yesterday',
    isRead: false,
  },
  {
    id: 'notif-6',
    type: 'follow',
    actorName: 'Neha Singh',
    message: 'started following you',
    avatarInitials: 'NS',
    avatarColor: 'var(--neutral)',
    timestamp: 'Yesterday',
    group: 'yesterday',
    isRead: true,
  },
];