// app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import { SessionBootstrap } from "@/shared/components/SessionBootstrap";

export const metadata: Metadata = {
  title: "Sangum",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full flex flex-col">
        <SessionBootstrap>{children}</SessionBootstrap>
      </body>
    </html>
  );
}